@baseUrl = http://localhost:8080
@json = application/json

### Health check
GET {{baseUrl}}/health

### Register User A
POST {{baseUrl}}/users/
Content-Type: {{json}}

{
  "username": "user-a2",
  "email": "a2@example.com",
  "password": "secret123"
}

### Register User B
POST {{baseUrl}}/users/
Content-Type: {{json}}

{
  "username": "user-b2",
  "email": "b2@example.com",
  "password": "secret123"
}

### Login User A
# После выполнения скопируйте token в переменную ниже.
POST {{baseUrl}}/users/login
Content-Type: {{json}}

{
  "username": "user-a2",
  "password": "secret123"
}

### Login User B
# После выполнения скопируйте token в переменную ниже.
POST {{baseUrl}}/users/login
Content-Type: {{json}}

{
  "username": "user-b2",
  "password": "secret123"
}

### Login Bootstrap Admin
# Логин и пароль по умолчанию: admin / admin123
# После выполнения скопируйте token в переменную ниже.
POST {{baseUrl}}/users/login
Content-Type: {{json}}

{
  "username": "admin",
  "password": "admin123"
}

### Tokens and IDs
@userAToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMWNiYjk2YjItMjc5My00NDM2LWIzY2UtMzU1NmEyNDg0MTExIiwicm9sZSI6InVzZXIiLCJleHAiOjE3NzYxMDY5OTAsImlhdCI6MTc3NjAyMDU5MH0.Nfisv_8Ol8TBGjjlNzbffMWY_T37bmY-Z5-5t05BHzI
@userBToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMWFlMzIzZmYtM2NiNC00OWUyLTkzNDgtZGM2OWU3ZGUwNTZiIiwicm9sZSI6InVzZXIiLCJleHAiOjE3NzYxMDcwMTQsImlhdCI6MTc3NjAyMDYxNH0.RsyMOqbU9iNQvceAEIG1YfeE8ps5hgHgmPXaYe9ReQU
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYmNjMmNlODUtODkxNy00OWM1LWIzMTUtNWFjMDBjNTMxN2VmIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzc2MTA3MDQyLCJpYXQiOjE3NzYwMjA2NDJ9.7vtof1kRue_uBy689mA2CpgvzQPgGGwtUaHoCnWjd18
@userBId = 1ae323ff-3cb4-49e2-9348-dc69e7de056b

### Get Me with User A token
GET {{baseUrl}}/users/me
Authorization: Bearer {{userAToken}}

### Get Me with User B token
GET {{baseUrl}}/users/me
Authorization: Bearer {{userBToken}}

### Protected hello with User A token
GET {{baseUrl}}/users/protected/hello
Authorization: Bearer {{userAToken}}

### Promote User B with regular user token
# Должен вернуть 403 Forbidden
PATCH {{baseUrl}}/users/promote/{{userBId}}
Authorization: Bearer {{userAToken}}

### Promote User B with admin token
# Должен вернуть 200 OK и role=admin
PATCH {{baseUrl}}/users/promote/{{userBId}}
Authorization: Bearer {{adminToken}}

### Rate limiter demo
GET {{baseUrl}}/health
