### 1. Попытка без ключа (Должно быть 401 Unauthorized)
GET http://localhost:8080/tasks

### 2. Попытка с правильным ключом (Должно работать)
GET http://localhost:8080/tasks
X-API-KEY: secret12345

### 3. Создание задачи с ключом (ОБЯЗАТЕЛЬНО пустая строка перед {)
POST http://localhost:8080/tasks
X-API-KEY: secret12345
Content-Type: application/json

{
  "title": "Сдать домашку"
}

### 4. Обновить задачу (поставить галочку)
PATCH http://localhost:8080/tasks?id=1
X-API-KEY: secret12345
Content-Type: application/json

{
  "done": true
}

### 5. Удалить задачу №1
DELETE http://localhost:8080/tasks?id=1
X-API-KEY: secret12345